# Generated by Django 2.0 on 2017-12-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("gifs", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="truckgifs",
            name="mp4url",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="truckgifs",
            name="preview",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
