# Generated by Django 2.0 on 2017-12-05 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("gifs", "0004_auto_20171205_1752")]

    operations = [
        migrations.RenameField(model_name="truckgif", old_name="mp4url", new_name="gif"),
        migrations.RenameField(model_name="truckgif", old_name="url", new_name="mp4"),
    ]
