# Generated by Django 2.0 on 2017-12-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("gifs", "0003_truckgifs_slug")]

    operations = [
        migrations.CreateModel(
            name="TruckGif",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("url", models.URLField()),
                ("mp4url", models.URLField()),
                ("preview", models.URLField()),
                ("title", models.TextField(max_length=60)),
                ("height", models.PositiveSmallIntegerField()),
                ("width", models.PositiveSmallIntegerField()),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.DeleteModel(name="TruckGifs"),
    ]
